commerce_payment.commerce_payment_gateway.plugin.payu_redirect_checkout:
  type: commerce_payment_gateway_configuration
  mapping:
    environment:
      type: string
      label: 'Environment'
    pos_id:
      type: string
      label: 'POS ID'
    signature_key:
      type: string
      label: 'Signature key'
    client_id:
      type: string
      label: 'Client ID'
    client_secret:
      type: string
      label: 'Client Secret'
